In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

Load Dataset

In [2]:
df = sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [4]:
df.shape #shows no. of rows & columns

(344, 7)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [8]:
df.isnull().sum()    #shows the null values.

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

Data Cleaning
Dropping the null values.

In [9]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum() #This shows that the null values have been dropped.

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

Data Manipulation/ Feature Engineering.

In [12]:
#Transforming categorical data into numeric.
'Using one-hot encoding, which is use of the pd.get_dummies'

In [28]:
 pd.get_dummies(df['sex']).head()

Female  Male
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [14]:
"from sklearn.preprocessing import Label_Encoder
label_encoder = Label_encoder()
df = label_encoder.fit_transform(categorical_data)"

SyntaxError: EOL while scanning string literal (1619671128.py, line 1)

In [30]:
#To drop the 1st column.
sex = pd.get_dummies(df['sex'], drop_first=True)
sex.head()

Male
0     1
1     0
2     0
4     0
5     1

In [16]:
#Applying One-hot encoding to the island column too.


In [17]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [20]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [31]:
island = pd.get_dummies(df['island'], drop_first=True)
island.head()

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [23]:
#We then Concatenate the 2 dataFrames into the original DF

In [32]:
new_data= pd.concat([df,island,sex], axis=1)

In [33]:
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Dream  Torgersen  Male  
0       3750.0    Male      0          1     1  
1       3800.0  Female      0          1     0  
2       3250.0  Female      0          1     0  
4       3450.0  Female      0          1     0  
5       3650.0    Male      0          1     1

In [34]:
#Dropping the Repeated Columns

In [37]:
new_data.drop(['sex','island'], axis=1, inplace=True);

In [46]:
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen  Male  
0      0          1     1  
1      0          1     0  
2      0          1     0  
4      0          1     0  
5      0          1     1

# Creating Separate target variable.

In [39]:
Y = new_data.species
Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [40]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [41]:
#since the data type is object, we will need to convert the data from categorical to numeric.
#Here we used the map function.
Y = Y.map({'Adelie':0, 'Chinstrap':1, 'Gentoo':2})

In [42]:
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

# Dropping the Target Variable: Species

In [47]:
new_data.drop(['species'], inplace= True, axis=1)

In [48]:
new_data.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0            39.1           18.7              181.0       3750.0      0   
1            39.5           17.4              186.0       3800.0      0   
2            40.3           18.0              195.0       3250.0      0   
4            36.7           19.3              193.0       3450.0      0   
5            39.3           20.6              190.0       3650.0      0   

   Torgersen  Male  
0          1     1  
1          1     0  
2          1     0  
4          1     0  
5          1     1

In [49]:
X = new_data

# Splitting the Data set into Training and Test Data

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3, random_state=0)
#The test size being 0.3, means I have splitted the data into 30% for testing and 70% for training.
# The random state being 0, means even when the code is run again, the values wont change since its not randomized.

In [51]:
print('X_train' , X_train.shape)
print( 'X_test' , X_test.shape)
print( 'Y_train' , Y_train.shape)
print( 'Y_test' , Y_test.shape)

X_train (233, 7)
X_test (100, 7)
Y_train (233,)
Y_test (100,)


# Training the Random Forest Classiffication on the Training set.

In [53]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5, criterion = 'entropy', random_state =0)
classifier.fit(X_train,Y_train)
#the n estimators refers to the number of Decesion trees in the random forest.

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

# Predicting the Test Results.

In [54]:
Y_pred = classifier.predict(X_test)
Y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

# Confusion Matrix and Accuracy score

In [55]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score

In [57]:
cm =confusion_matrix(Y_test, Y_pred)
print(cm)

[[48  0  0]
 [ 2 14  0]
 [ 0  0 36]]


In [58]:
accuracy_score(Y_test,Y_pred)

0.98

In [59]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100



# Trying with Different no. of trees and Giny Criteria.

In [63]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 7, criterion = 'gini', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [64]:
Y_pred = classifier.predict(X_test)

In [65]:
confusion_matrix(Y_pred, Y_test)

array([[48,  1,  0],
       [ 0, 15,  0],
       [ 0,  0, 36]], dtype=int64)

In [66]:
accuracy_score(Y_test,Y_pred)

0.99